version: "3"
services:
  flatnotes:
    image: bubuzi/flatnotes:0.0.1
    container_name: flatnotes
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: linux/amd64  
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "bubuzi"
      FLATNOTES_PASSWORD: "bubuzi169"
      FLATNOTES_SECRET_KEY: "amnSOgscsCeifraeRtonLrhadoera"
    volumes:
      - "./data:/data" 
    ports:
      - "40080:8080"
    restart: unless-stopped
