version: "3"
services:
  flatnotes:
    container_name: flatnotes
    build:
      context: .
    dockerfile: Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "bubuzi"
      FLATNOTES_PASSWORD: "bubuzi169"
      FLATNOTES_SECRET_KEY: "amnSOgscsCeifraeRtonLrhadoera"
    volumes:
      - "./data:/data"
      # Optional. Allows you to save the search index in a different location: 
      # - "./index:/data/.flatnotes"
    ports:
      - "40080:8080"
    restart: unless-stopped
